#!/bin/sh

case "$1" in
    start)
        echo "Loading LDD modules"
        # Load scull driver
        cd /usr/bin && ./scull_load
        
        # Load faulty driver
        cd /usr/bin && ./module_load faulty
        
        # Load hello module
        modprobe hello
        
        ;;
    stop)
        echo "Unloading LDD modules"
        # Unload hello module
        rmmod hello
        
        # Unload faulty driver
        cd /usr/bin && ./module_unload faulty
        
        # Unload scull driver
        cd /usr/bin && ./scull_unload
        
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0